-- MOV Valve matcode_master 등록
-- Supabase SQL Editor에서 실행
SET search_path TO material, public;

INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-AS91-D010-C1500-SW', 'Valve', 'MOV (GLOBE)', 'A182-F91 (Alloy Steel Cr-Mo)', '1"', '', 'CL1500', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-AS91-D020-C1500-SW', 'Valve', 'MOV (GLOBE)', 'A182-F91 (Alloy Steel Cr-Mo)', '2"', '', 'CL1500', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-AS91-D030-C1500-BW', 'Valve', 'MOV (GLOBE)', 'A182-F91 (Alloy Steel Cr-Mo)', '3"', '', 'CL1500', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-AS91-D040-C1500-BW', 'Valve', 'MOV (GATE)', 'A182-F91 (Alloy Steel Cr-Mo)', '4"', '', 'CL1500', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D010-C1500-SW', 'Valve', 'MOV (GLOBE)', 'A105 / A216-WCB (Carbon Steel)', '1"', '', 'CL1500', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D010-C600-SW', 'Valve', 'MOV (GLOBE)', 'A105 / A216-WCB (Carbon Steel)', '1"', '', 'CL600', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D020-C600-SW', 'Valve', 'MOV (GLOBE)', 'A105 / A216-WCB (Carbon Steel)', '2"', '', 'CL600', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D030-C600-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '3"', '', 'CL600', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D040-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A105 / A216-WCB (Carbon Steel)', '4"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D060-C150-BW', 'Valve', 'MOV (GLOBE)', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D060-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D060-C1500-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL1500', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D060-C300-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL300', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D080-C300-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '8"', '', 'CL300', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D100-C300-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '10"', '', 'CL300', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D140-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A105 / A216-WCB (Carbon Steel)', '14"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D160-C150-BW', 'Valve', 'MOV (GATE)', 'A105 / A216-WCB (Carbon Steel)', '16"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-CS05-D200-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A105 / A216-WCB (Carbon Steel)', '20"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-SS04-D010-C600-SW', 'Valve', 'MOV (GLOBE)', 'A351-CF8 (Stainless Steel 304)', '1"', '', 'CL600', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-SS04-D030-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A351-CF8 (Stainless Steel 304)', '3"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-SS04-D060-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A351-CF8 (Stainless Steel 304)', '6"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-SS04-D080-C150-BW', 'Valve', 'MOV (GATE)', 'A351-CF8 (Stainless Steel 304)', '8"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('MOV-SS04-D100-C150-RF', 'Valve', 'MOV (BUTTERFLY VALVE)', 'A351-CF8 (Stainless Steel 304)', '10"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
