-- Safety Valve + Control Valve BOM INSERT
-- Supabase SQL Editor에서 실행

-- Safety Valve / Control Valve BOM 기존 데이터 삭제
DELETE FROM material.bom
WHERE category = 'Valve'
  AND tag ~ '^B[012w][-]?(PSV|TCV|LCV|FCV|FV|PCV)';

-- Safety Valve (43행)
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-28191', 'AS', NULL, NULL, 'Pressure Safety Valve, DN 150, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-28191', 'AS', NULL, NULL, 'Pressure Safety Valve, DN 150, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-30192', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-30192', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-31192', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-31192', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-30193', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-30193', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-301193', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-301193', 'FG', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV-34006', 'HW', NULL, NULL, 'Pressure Safety Valve, DN 200, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV-34006', 'HW', NULL, NULL, 'Pressure Safety Valve, DN 200, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32001', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32001', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32006', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32006', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32002', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32003', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32004', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32005', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32007', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32008', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32009', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32010', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32002', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32003', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32004', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32005', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32007', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32008', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32009', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32010', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32011', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32012', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PSV32013', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32011', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32012', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PSV32013', 'CCW', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PSV-46191', 'FO', NULL, NULL, 'Pressure Safety Valve, DN 50, SA351-CF8, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PSV-46192', 'FO', NULL, NULL, 'Pressure Safety Valve, DN 50, SA351-CF8, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PSV-46193', 'FO', NULL, NULL, 'Pressure Safety Valve, DN 50, SA216-WCB, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PSV-46195', 'FO', NULL, NULL, 'Pressure Safety Valve, DN 50, A351-CF8, ASME 150# RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PSV-46194', 'FO', NULL, NULL, 'Pressure Safety Valve, DN 50, A351-CF8, ASME 150# RF', 'EA', 1.0);

-- Control Valve (52행)
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-33081', 'B1', NULL, NULL, 'FLSH TK SPRY TCV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-33081', 'B2', NULL, NULL, 'FLSH TK SPRY TCV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-LCV-33081', 'B1', NULL, NULL, 'FLSH TK DRN PP DISCH HDR LCV, GLOBE, DN 80, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-LCV-33081', 'B2', NULL, NULL, 'FLSH TK DRN PP DISCH HDR LCV, GLOBE, DN 80, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-LCV-29081', 'B1', NULL, NULL, 'COND DUMP LCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-LCV-29081', 'B2', NULL, NULL, 'COND DUMP LCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FCV-29082', 'B1', NULL, NULL, 'CEP MIN RECIRC FCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FCV-29082', 'B2', NULL, NULL, 'CEP MIN RECIRC FCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-LCV-35083', 'B1', NULL, NULL, 'COND COLLN TK MU LCV, GLOBE, DN 80, A351-CF8, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-LCV-35083', 'B2', NULL, NULL, 'COND COLLN TK MU LCV, GLOBE, DN 80, A351-CF8, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FCV-30081A', 'B1', NULL, NULL, 'FWP-A MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FCV-30081A', 'B2', NULL, NULL, 'FWP-A MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FCV-31081A', 'B1', NULL, NULL, 'FWP-A MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FCV-31081A', 'B2', NULL, NULL, 'FWP-A MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FCV-30081B', 'B1', NULL, NULL, 'FWP-B MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FCV-30081B', 'B2', NULL, NULL, 'FWP-B MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FCV-31081B', 'B1', NULL, NULL, 'FWP-B MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FCV-31081B', 'B2', NULL, NULL, 'FWP-B MIN RECIRC FCV, GLOBE, DN 100, A216-WCC, 1500#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-30082', 'B1', NULL, NULL, 'GT PERFORM HTR TO CPH TCV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-30082', 'B2', NULL, NULL, 'GT PERFORM HTR TO CPH TCV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-31082', 'B1', NULL, NULL, 'GT PERFORM HTR TO CPH TCV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-31082', 'B2', NULL, NULL, 'GT PERFORM HTR TO CPH TCV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-30051', 'B1', NULL, NULL, 'GT PERFORM HTR INL XV (MN), GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-30051', 'B2', NULL, NULL, 'GT PERFORM HTR INL XV (MN), GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-31051', 'B1', NULL, NULL, 'GT PERFORM HTR INL XV (MN), GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-31051', 'B2', NULL, NULL, 'GT PERFORM HTR INL XV (MN), GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-30052', 'B1', NULL, NULL, 'GT PERFORM HTR INL XV (EQ), GLOBE, DN 25, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'Bw-FV-30052', NULL, NULL, NULL, 'GT PERFORM HTR INL XV (EQ), GLOBE, DN 25, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-31052', 'B1', NULL, NULL, 'GT PERFORM HTR INL XV (EQ), GLOBE, DN 25, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-31052', 'B2', NULL, NULL, 'GT PERFORM HTR INL XV (EQ), GLOBE, DN 25, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-30053', 'B1', NULL, NULL, 'GT PERFORM HTR OUTL XV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-30053', 'B2', NULL, NULL, 'GT PERFORM HTR OUTL XV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-31053', 'B1', NULL, NULL, 'GT PERFORM HTR OUTL XV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-31053', 'B2', NULL, NULL, 'GT PERFORM HTR OUTL XV, GLOBE, DN 80, A216-WCB, 600#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-30054', 'B1', NULL, NULL, 'GT FUEL GAS LEAK VT XV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-30054', 'B2', NULL, NULL, 'GT FUEL GAS LEAK VT XV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-FV-31054', 'B1', NULL, NULL, 'GT FUEL GAS LEAK VT XV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-FV-31054', 'B2', NULL, NULL, 'GT FUEL GAS LEAK VT XV, GLOBE, DN 50, A105, 600#, SW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-PCV-34084', 'B1', NULL, NULL, 'AUX STM TO HOT WTR HTR PCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-PCV-34084', 'B2', NULL, NULL, 'AUX STM TO HOT WTR HTR PCV, GLOBE, DN 150, A216-WCB, 300#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-LCV-34083', 'B1', NULL, NULL, 'HOT WTR HTR DRN LCV, GLOBE, DN 100, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-LCV-34083', 'B2', NULL, NULL, 'HOT WTR HTR DRN LCV, GLOBE, DN 100, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-34085', 'B1', NULL, NULL, 'HOT WTR DIST 3-WAY TCV, 3WAY GLOBE, DN 200, A216-WCB, 150#, RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-34085', 'B2', NULL, NULL, 'HOT WTR DIST 3-WAY TCV, 3WAY GLOBE, DN 200, A216-WCB, 150#, RF', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PCV-38017', 'B0', NULL, NULL, 'RAW WTR DIST PP RECIRC PCV, GLOBE, DN 100, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PCV-36017', 'B0', NULL, NULL, 'SERV WTR DIST PP RECIRC PCV, GLOBE, DN 80, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PCV-37017', 'B0', NULL, NULL, 'POTB WTR DIST PP RECIRC PCV, GLOBE, DN 100, A351-CF8, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B0-PCV-46081', 'B0', NULL, NULL, 'FO XFP RECIRC PCV, GLOBE, DN 250, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-32001', 'B1', NULL, NULL, 'CCW GT LO INL TCV, GLOBE, DN 200, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-32001', 'B2', NULL, NULL, 'CCW GT LO INL TCV, GLOBE, DN 200, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B1-TCV-32002', 'B1', NULL, NULL, 'CCW GT LO INL TCV, GLOBE, DN 200, A216-WCB, 150#, BW', 'EA', 1.0);
INSERT INTO material.bom (mat_code, category, tag, system, iso_dwg_no, line_no, full_description, uom, qty) VALUES (NULL, 'Valve', 'B2-TCV-32002', 'B2', NULL, NULL, 'CCW GT LO INL TCV, GLOBE, DN 200, A216-WCB, 150#, BW', 'EA', 1.0);
