-- Safety Valve / Control Valve matcode_master 등록
-- Supabase SQL Editor에서 실행

INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D010-C600-SW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '1"', '', 'CL600', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D020-C600-SW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '2"', '', 'CL600', 'SW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D030-C150-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '3"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D030-C600-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '3"', '', 'CL600', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D040-C150-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '4"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D040-C1500-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '4"', '', 'CL1500', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D060-C300-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL300', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D080-C150-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '8"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D080-C150-RF', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '8"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-CS05-D100-C150-BW', 'Valve', 'CONTROL VALVE', 'A105 / A216-WCB (Carbon Steel)', '10"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-SS04-D030-C150-BW', 'Valve', 'CONTROL VALVE', 'A351-CF8 (Stainless Steel 304)', '3"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('CON-SS04-D040-C150-BW', 'Valve', 'CONTROL VALVE', 'A351-CF8 (Stainless Steel 304)', '4"', '', 'CL150', 'BW') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('PSV-CS05-D020-C150-RF', 'Valve', 'SAFETY VALVE', 'A105 / A216-WCB (Carbon Steel)', '2"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('PSV-CS05-D060-C150-RF', 'Valve', 'SAFETY VALVE', 'A105 / A216-WCB (Carbon Steel)', '6"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('PSV-CS05-D080-C150-RF', 'Valve', 'SAFETY VALVE', 'A105 / A216-WCB (Carbon Steel)', '8"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
INSERT INTO material.matcode_master (mat_code, category, item_desc, matl_desc, size1, size2, class_desc, et_desc) VALUES ('PSV-SS04-D020-C150-RF', 'Valve', 'SAFETY VALVE', 'A351-CF8 (Stainless Steel 304)', '2"', '', 'CL150', 'RF') ON CONFLICT (mat_code) DO NOTHING;
